{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "socle.fullname" . }}-backend
  labels:
    {{- include "socle.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "socle.backend.selectorLabels" . | nindent 6 }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "socle.fullname" . }}-frontend
  labels:
    {{- include "socle.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "socle.frontend.selectorLabels" . | nindent 6 }}
{{- end }}
