apiVersion: v1
kind: Service
metadata:
  name: {{ include "socle.fullname" . }}-backend
  labels:
    {{- include "socle.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    {{- include "socle.backend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "socle.fullname" . }}-frontend
  labels:
    {{- include "socle.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "socle.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
